config/routes.rb
Rails.application.routes.draw do
  root :to => 'microcosms#index'

  get '/sessions/new' => 'sessions#new'
  match '/auth/:provider/callback' => "sessions#create", via: [:get, :post]
  match '/auth/failure', to: redirect('/'), via: [:get, :post]
  match '/signout' => 'sessions#destroy', :as => :signout, via: [:get, :post]
  resources :events
  resources :organizers
  # This is needed because "new" matches the regex for microcosm names.
  get 'microcosms/new', to: 'microcosms#new'
  get 'microcosms/:key', to: 'microcosms#show_by_key', constraints: { key: /[a-zA-Z]{1,32}/ }
  # TODO: use key by setting constraints:.
  get 'microcosms/:id/editors', to: 'microcosms#show_editors', :as => :editors_of_microcosm
  get 'microcosms/:id/changesets', to: 'microcosms#show_changesets', :as => :changesets_of_microcosm
  get 'microcosms/:id/organizers', to: 'microcosms#show_organizers', :as => :organizers_of_microcosm
  get 'microcosms/:id/members', to: 'microcosms#show_members', :as => :members_of_microcosm
  get 'microcosms/:id/welcome/:editor_id', to: 'microcosms#welcome_editor_form', :as => :welcome_editor_form
  post 'microcosms/:id/welcome/:editor_id', to: 'microcosms#welcome_editor', :as => :welcome_editor
  post '/microcosms/discover_changesets', to: 'microcosms#discover_changesets'
  resources :microcosms
  resources :microcosm_changesets
  resources :members
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/organizer.rb
class Organizer < ApplicationRecord
  belongs_to :microcosm
  belongs_to :user
end

app/controllers/organizers_controller.rb
class OrganizersController < ApplicationController
  before_action :set_organizer, only: [:show, :edit, :update, :destroy]

  # GET /organizers
  # GET /organizers.json
  def index
    @organizers = Organizer.all
  end

  # GET /organizers/1
  # GET /organizers/1.json
  def show
  end

  # GET /organizers/new
  def new
    @organizer = Organizer.new
    @organizer.microcosm_id = params[:microcosm_id]
    @organizer.user_id = params[:user_id]
  end

  # GET /organizers/1/edit
  def edit
  end

  # POST /organizers
  # POST /organizers.json
  def create
    @organizer = Organizer.new(organizer_params)

    respond_to do |format|
      if @organizer.save
        format.html { redirect_to @organizer, notice: 'Organizer was successfully created.' }
        format.json { render :show, status: :created, location: @organizer }
      else
        format.html { render :new }
        format.json { render json: @organizer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizers/1
  # PATCH/PUT /organizers/1.json
  def update
    respond_to do |format|
      if @organizer.update(organizer_params)
        format.html { redirect_to @organizer, notice: 'Organizer was successfully updated.' }
        format.json { render :show, status: :ok, location: @organizer }
      else
        format.html { render :edit }
        format.json { render json: @organizer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizers/1
  # DELETE /organizers/1.json
  def destroy
    @organizer.destroy
    respond_to do |format|
      format.html { redirect_to organizers_url, notice: 'Organizer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organizer
      @organizer = Organizer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organizer_params
      params.require(:organizer).permit(:microcosm_id, :user_id)
    end
end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/views/organizers/_form.html.erb
<%= form_with(model: organizer, local: true) do |form| %>
  <% if organizer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organizer.errors.count, "error") %> prohibited this organizer from being saved:</h2>

      <ul>
      <% organizer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :microcosm_id %>
    <%= collection_select(:organizer, :microcosm_id, Microcosm.all, :id, :name, :prompt => true) %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= collection_select(:organizer, :user_id, User.order('name').all, :id, :name, :prompt => true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/organizers/edit.html.erb
<h1>Editing Organizer</h1>

<%= render 'form', organizer: @organizer %>

<%= link_to 'Show', @organizer %> |
<%= link_to 'Back', organizers_path %>

app/views/organizers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organizers</h1>

<table>
  <thead>
    <tr>
      <th>Microcosm</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizers.each do |organizer| %>
      <tr>
        <td><%= organizer.microcosm_id %></td>
        <td><%= organizer.user_id %></td>
        <td><%= link_to 'Show', organizer %></td>
        <td><%= link_to 'Edit', edit_organizer_path(organizer) %></td>
        <td><%= link_to 'Destroy', organizer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organizer', new_organizer_path %>

app/views/organizers/new.html.erb
<h1>New Organizer</h1>

<%= render 'form', organizer: @organizer %>

<%= link_to 'Back', organizers_path %>

app/views/organizers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Microcosm:</strong>
  <%= @organizer.microcosm_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @organizer.user_id %>
</p>

<%= link_to 'Edit', edit_organizer_path(@organizer) %> |
<%= link_to 'Back', organizers_path %>