config/routes.rb
Rails.application.routes.draw do
  root :to => 'microcosms#index'

  get '/sessions/new' => 'sessions#new'
  match '/auth/:provider/callback' => "sessions#create", via: [:get, :post]
  match '/auth/failure', to: redirect('/'), via: [:get, :post]
  match '/signout' => 'sessions#destroy', :as => :signout, via: [:get, :post]
  resources :events
  resources :organizers
  # This is needed because "new" matches the regex for microcosm names.
  get 'microcosms/new', to: 'microcosms#new'
  get 'microcosms/:key', to: 'microcosms#show_by_key', constraints: { key: /[a-zA-Z]{1,32}/ }
  # TODO: use key by setting constraints:.
  get 'microcosms/:id/editors', to: 'microcosms#show_editors', :as => :editors_of_microcosm
  get 'microcosms/:id/changesets', to: 'microcosms#show_changesets', :as => :changesets_of_microcosm
  get 'microcosms/:id/organizers', to: 'microcosms#show_organizers', :as => :organizers_of_microcosm
  get 'microcosms/:id/members', to: 'microcosms#show_members', :as => :members_of_microcosm
  get 'microcosms/:id/welcome/:editor_id', to: 'microcosms#welcome_editor_form', :as => :welcome_editor_form
  post 'microcosms/:id/welcome/:editor_id', to: 'microcosms#welcome_editor', :as => :welcome_editor
  post '/microcosms/discover_changesets', to: 'microcosms#discover_changesets'
  resources :microcosms
  resources :microcosm_changesets
  resources :members
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/changeset.rb
class Changeset < ApplicationRecord
end

app/models/osm/changeset.rb
class Osm::Changeset < ApplicationRecord
  belongs_to :user, class_name: 'Osm::User'
  establish_connection(:osm)
end

app/controllers/changesets_controller.rb
class ChangesetsController < ApplicationController
  before_action :set_changeset, only: [:show, :edit, :update, :destroy]

  # GET /changesets
  # GET /changesets.json
  def index
    @changesets = Changeset.all
  end

  # GET /changesets/1
  # GET /changesets/1.json
  def show
  end

  # GET /changesets/new
  def new
    @changeset = Changeset.new
  end

  # GET /changesets/1/edit
  def edit
  end

  # POST /changesets
  # POST /changesets.json
  def create
    @changeset = Changeset.new(changeset_params)

    respond_to do |format|
      if @changeset.save
        format.html { redirect_to @changeset, notice: 'Changeset was successfully created.' }
        format.json { render :show, status: :created, location: @changeset }
      else
        format.html { render :new }
        format.json { render json: @changeset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /changesets/1
  # PATCH/PUT /changesets/1.json
  def update
    respond_to do |format|
      if @changeset.update(changeset_params)
        format.html { redirect_to @changeset, notice: 'Changeset was successfully updated.' }
        format.json { render :show, status: :ok, location: @changeset }
      else
        format.html { render :edit }
        format.json { render json: @changeset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /changesets/1
  # DELETE /changesets/1.json
  def destroy
    @changeset.destroy
    respond_to do |format|
      format.html { redirect_to changesets_url, notice: 'Changeset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_changeset
      @changeset = Changeset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def changeset_params
      params.require(:changeset).permit(:user_id, :created_at, :min_lat, :max_lat, :min_lon, :max_lon, :closed_at, :num_changes)
    end
end

app/helpers/changesets_helper.rb
module ChangesetsHelper
end

app/views/changesets/_form.html.erb
<%= form_with(model: changeset, local: true) do |form| %>
  <% if changeset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(changeset.errors.count, "error") %> prohibited this changeset from being saved:</h2>

      <ul>
      <% changeset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :changeset_user_id %>
  </div>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.datetime_select :created_at, id: :changeset_created_at %>
  </div>

  <div class="field">
    <%= form.label :min_lat %>
    <%= form.number_field :min_lat, id: :changeset_min_lat %>
  </div>

  <div class="field">
    <%= form.label :max_lat %>
    <%= form.number_field :max_lat, id: :changeset_max_lat %>
  </div>

  <div class="field">
    <%= form.label :min_lon %>
    <%= form.number_field :min_lon, id: :changeset_min_lon %>
  </div>

  <div class="field">
    <%= form.label :max_lon %>
    <%= form.number_field :max_lon, id: :changeset_max_lon %>
  </div>

  <div class="field">
    <%= form.label :closed_at %>
    <%= form.datetime_select :closed_at, id: :changeset_closed_at %>
  </div>

  <div class="field">
    <%= form.label :num_changes %>
    <%= form.number_field :num_changes, id: :changeset_num_changes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/changesets/edit.html.erb
<h1>Editing Changeset</h1>

<%= render 'form', changeset: @changeset %>

<%= link_to 'Show', @changeset %> |
<%= link_to 'Back', changesets_path %>

app/views/changesets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Changesets</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Created at</th>
      <th>Min lat</th>
      <th>Max lat</th>
      <th>Min lon</th>
      <th>Max lon</th>
      <th>Closed at</th>
      <th>Num changes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @changesets.each do |changeset| %>
      <tr>
        <td><%= changeset.user_id %></td>
        <td><%= changeset.created_at %></td>
        <td><%= changeset.min_lat %></td>
        <td><%= changeset.max_lat %></td>
        <td><%= changeset.min_lon %></td>
        <td><%= changeset.max_lon %></td>
        <td><%= changeset.closed_at %></td>
        <td><%= changeset.num_changes %></td>
        <td><%= link_to 'Show', changeset %></td>
        <td><%= link_to 'Edit', edit_changeset_path(changeset) %></td>
        <td><%= link_to 'Destroy', changeset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Changeset', new_changeset_path %>

app/views/changesets/new.html.erb
<h1>New Changeset</h1>

<%= render 'form', changeset: @changeset %>

<%= link_to 'Back', changesets_path %>

app/views/changesets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @changeset.user_id %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @changeset.created_at %>
</p>

<p>
  <strong>Min lat:</strong>
  <%= @changeset.min_lat %>
</p>

<p>
  <strong>Max lat:</strong>
  <%= @changeset.max_lat %>
</p>

<p>
  <strong>Min lon:</strong>
  <%= @changeset.min_lon %>
</p>

<p>
  <strong>Max lon:</strong>
  <%= @changeset.max_lon %>
</p>

<p>
  <strong>Closed at:</strong>
  <%= @changeset.closed_at %>
</p>

<p>
  <strong>Num changes:</strong>
  <%= @changeset.num_changes %>
</p>

<%= link_to 'Edit', edit_changeset_path(@changeset) %> |
<%= link_to 'Back', changesets_path %>