config/routes.rb
Rails.application.routes.draw do
  root :to => 'microcosms#index'

  get '/sessions/new' => 'sessions#new'
  match '/auth/:provider/callback' => "sessions#create", via: [:get, :post]
  match '/auth/failure', to: redirect('/'), via: [:get, :post]
  match '/signout' => 'sessions#destroy', :as => :signout, via: [:get, :post]
  resources :events
  resources :organizers
  # This is needed because "new" matches the regex for microcosm names.
  get 'microcosms/new', to: 'microcosms#new'
  get 'microcosms/:key', to: 'microcosms#show_by_key', constraints: { key: /[a-zA-Z]{1,32}/ }
  # TODO: use key by setting constraints:.
  get 'microcosms/:id/editors', to: 'microcosms#show_editors', :as => :editors_of_microcosm
  get 'microcosms/:id/changesets', to: 'microcosms#show_changesets', :as => :changesets_of_microcosm
  get 'microcosms/:id/organizers', to: 'microcosms#show_organizers', :as => :organizers_of_microcosm
  get 'microcosms/:id/members', to: 'microcosms#show_members', :as => :members_of_microcosm
  get 'microcosms/:id/welcome/:editor_id', to: 'microcosms#welcome_editor_form', :as => :welcome_editor_form
  post 'microcosms/:id/welcome/:editor_id', to: 'microcosms#welcome_editor', :as => :welcome_editor
  post '/microcosms/discover_changesets', to: 'microcosms#discover_changesets'
  resources :microcosms
  resources :microcosm_changesets
  resources :members
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/microcosm.rb
class Microcosm < ApplicationRecord
  has_many :members
  has_many :users, through: :members
  has_many :organizers
  has_many :org_users, through: :organizers
  has_many :events
  has_many :microcosm_changesets
  has_many :changesets, through: :microcosm_changesets

  validates :description, format: { without: /[<>]/, message: "HTML tags are not allowed." }, length: { maximum: 500, too_long: "%{count} characters is the maximum allowed" }

  validates :welcome_message, format: { without: /[<>]/, message: "HTML tags are not allowed." }, length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed" }
end

app/controllers/microcosms_controller.rb
class MicrocosmsController < ApplicationController
  before_action :set_microcosm, only: [:show, :show_editors, :show_changesets, :show_organizers, :show_members, :edit, :update, :destroy, :welcome_editor, :welcome_editor_form]
  before_action :set_microcosm_by_key, only: [:show_by_key]
  before_action :authenticate, :except => [:index, :show, :show_by_key]  # TODO inherit
  helper_method :recent_first_editors
  helper_method :current_changesets
  helper_method :organizer_names

  # GET /microcosms
  # GET /microcosms.json
  def index
    @microcosms = Microcosm.order(:name)
  end

  # GET /microcosms/1
  # GET /microcosms/1.json
  def show
  end

  # GET /microcosms/mycity
  # GET /microcosms/mycity.json
  def show_by_key
    render action: "show"
  end

  def show_editors
  end

  def show_changesets
  end

  def show_organizers
  end

  def show_members
  end

  # GET /microcosms/new
  def new
    @microcosm = Microcosm.new
  end

  # GET /microcosms/1/edit
  def edit
  end

  # POST /microcosms
  # POST /microcosms.json
  def create
    @microcosm = Microcosm.new(microcosm_params)

    respond_to do |format|
      if @microcosm.save
        format.html { redirect_to @microcosm, notice: 'Microcosm was successfully created.' }
        format.json { render :show, status: :created, location: @microcosm }
      else
        format.html { render :new }
        format.json { render json: @microcosm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microcosms/1
  # PATCH/PUT /microcosms/1.json
  def update
    respond_to do |format|
      if @microcosm.update(microcosm_params)
        format.html { redirect_to @microcosm, notice: 'Microcosm was successfully updated.' }
        format.json { render :show, status: :ok, location: @microcosm }
      else
        format.html { render :edit }
        format.json { render json: @microcosm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microcosms/1
  # DELETE /microcosms/1.json
  def destroy
    @microcosm.destroy
    respond_to do |format|
      format.html { redirect_to microcosms_url, notice: 'Microcosm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def recent_first_editors
    @rfe = User.includes(:first_edit).order('uid::int desc').first(40)
  end


  def current_changesets
    MicrocosmChangeset.includes(:user).where(microcosm_id: @microcosm.id).where(review_num: 0).last(10)
  end


  def organizer_names
    @microcosm.organizers.map { |organizer|
#     names = organizer.user.name.split(' ')
#     names.first + ' ' + names.last.first
      organizer.user.name
    }.join(', ')
  end


  def discover_changesets
    @microcosm = Microcosm.find(params[:microcosm_id])
    # Get the greatest known changeset_id for this microcosm.
    max_id = MicrocosmChangeset.where(microcosm_id: @microcosm.id).maximum('changeset_id') || 0
    count_default = 10;
    count_max = 10000
    limit = [params.fetch(:count, count_default).to_i, count_max].min
    Osm::Changeset.where("? < max_lon and min_lon < ? and ? < max_lat and min_lat < ?", @microcosm.min_lon, @microcosm.max_lon, @microcosm.min_lat, @microcosm.max_lat).where("? < id", max_id).order(:id).limit(limit).each do |changeset|
      # Copy the user
      osm_user = Osm::User.find(changeset.user_id)
      u = User.find_or_create_by(uid: changeset.user_id) do |u|
        u.uid = changeset.user_id
        u.name = osm_user.display_name
        u.created_at = osm_user.creation_time
        u.updated_at = osm_user.creation_time
      end
      # TODO: Use default value for review_num.
      mc = MicrocosmChangeset.new(microcosm_id: @microcosm.id, changeset_id: changeset.id, user_id: u.id, review_num: 0)
      mc.save(validate: false)
    end
    render action: "show"
  end


  def welcome_editor
    editor = User.find(params[:editor_id])
    editor.welcomed = true
    editor.save
    redirect_to @microcosm
  end


  def welcome_editor_form
    @editor = User.find(params[:editor_id])
    @subject = 'Welcome to OpenStreetMap'
    @welcome_message = @microcosm.welcome_message.sub! '{{name}}', @editor.name
    @qs = URI.encode_www_form([['message[title]', @subject], ['message[body]', @welcome_message]])
    render 'welcome_editor_form'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_microcosm
      @microcosm = Microcosm.find(params[:id])
    end

    def set_microcosm_by_key
      @microcosm = Microcosm.find_by(key: params[:key])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def microcosm_params
      params.require(:microcosm).permit(:name, :key, :facebook, :twitter, :lat, :lon, :min_lat, :max_lat, :min_lon, :max_lon, :description, :welcome_message)
    end
end

app/helpers/microcosms_helper.rb
module MicrocosmsHelper
end

app/views/microcosms/_form.html.erb
<%= form_with(model: microcosm, local: true) do |form| %>
  <% if microcosm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(microcosm.errors.count, "error") %> prohibited this microcosm from being saved:</h2>

      <ul>
      <% microcosm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :microcosm_name %>
  </div>

  <div class="field">
    <%= form.label :key %>
    <%= form.text_field :key, id: :microcosm_key %>
  </div>

  <div class="field">
    <%= form.label :facebook %>
    <%= form.text_field :facebook, id: :microcosm_facebook %>
  </div>

  <div class="field">
    <%= form.label :twitter %>
    <%= form.text_field :twitter, id: :microcosm_twitter %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat, id: :microcosm_lat %> (decimal)
  </div>

  <div class="field">
    <%= form.label :lon %>
    <%= form.text_field :lon, id: :microcosm_lon %> (decimal)
  </div>

  <p>
To get a bounding box use Geofabrik's <a href="http://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=-120.848658,31.674368,-79.375023,49.413863&tab=1&proj=EPSG:4326&places=2">Tile Calculator</a> tool.
  </p>

  <div class="field">
    <%= form.label :min_lat %>
    <%= form.text_field :min_lat, id: :microcosm_min_lat %> (decimal * 10^7)
  </div>

  <div class="field">
    <%= form.label :max_lat %>
    <%= form.text_field :max_lat, id: :microcosm_max_lat %> (decimal * 10^7)
  </div>

  <div class="field">
    <%= form.label :min_lon %>
    <%= form.text_field :min_lon, id: :microcosm_min_lon %> (decimal * 10^7)
  </div>

  <div class="field">
    <%= form.label :max_lon %>
    <%= form.text_field :max_lon, id: :microcosm_max_lon %> (decimal * 10^7)
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :microcosm_description %> (decimal * 10^7)
  </div>

  <div class="field">
    <%= form.label :welcome_message %>
    <%= form.text_area :welcome_message, id: :microcosm_welcome_message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/microcosms/edit.html.erb
<h1>Editing Microcosm</h1>

<%= render 'form', microcosm: @microcosm %>

<%= link_to 'Show', @microcosm %> |
<%= link_to 'Back', microcosms_path %>

app/views/microcosms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Microcosms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Key</th>
      <th>Members</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microcosms.each do |microcosm| %>
      <tr>
        <td><%= microcosm.name %></td>
        <td><%= microcosm.key %></td>
        <td><%= microcosm.members.size %></td>
        <td><%= link_to 'Show', microcosm %></td>
        <td><%= link_to 'Edit', edit_microcosm_path(microcosm) %></td>
        <td><%= link_to 'Destroy', microcosm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Microcosm', new_microcosm_path %>

app/views/microcosms/new.html.erb
<h1>New Microcosm</h1>

<%= render 'form', microcosm: @microcosm %>

<%= link_to 'Back', microcosms_path %>

app/views/microcosms/show.html.erb
<p id="notice"><%= notice %></p>

<div class='mc-row'>
<%= map(:container_id => 'Map',
  :center => {
  :latlng => [@microcosm.lat, @microcosm.lon],
  :zoom => 11
}) %>
  <div id='Details'>
    <h1>
<%= link_to @microcosm.name, @microcosm %> <%= link_to 'Edit', edit_microcosm_path(@microcosm), :class => 'edit_link' %>
    </h1>
    <p>
<%= auto_link @microcosm.description %>
    </p>
    <p>
<label>Organizers</label> <strong><%= link_to organizer_names, organizers_of_microcosm_path(@microcosm) %></strong>
    </p>
    <p>
<label>Members</label> <strong><%= link_to @microcosm.members.size, members_of_microcosm_path(@microcosm) %></strong>
    </p>
    <% unless @microcosm.facebook.nil? and @microcosm.twitter.nil? %>
        <p>
<label>Share</label>
        <% unless @microcosm.facebook.nil? %>
<strong><a href="https://facebook.com/groups/<%=@microcosm.facebook%>">Facebook</a></strong>
        <% end %>
        <% unless @microcosm.twitter.nil? %>
<strong><a href="https://twitter.com/<%=@microcosm.twitter%>">Twitter</a></strong>
        <% end %>
        </p>
    <% end %>
    <p>
<%= link_to 'Changesets', changesets_of_microcosm_path(@microcosm) %>, <%= link_to 'Editors', editors_of_microcosm_path(@microcosm) %>
    </p>
  </div>
</div>

<div class='mc-row'>
  <div id='Members'>
    <h2>
<%= link_to 'Members', members_of_microcosm_path(@microcosm) %> <%= link_to 'New', new_member_path(microcosm_id: @microcosm.id), :class => 'new_link' %>
    </h2>
    <div class='members'>
      <% @microcosm.members.each do |member| %>
          <%= link_to member.user.name, user_path(member.user) %>
      <% end %>
    </div>
  </div>
  <div id='Events'>
    <h2>
Upcoming Events <%= link_to 'New', new_event_path(microcosm_id: @microcosm.id), :class => 'new_link' %>
    </h2>
    <div class='events'>
      <ul>
        <% @microcosm.events.each do |event| %>
          <li><%= event.moment %> - <%= event.title %> - <%= event.location %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/microcosms/show_changesets.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @microcosm.name %>
</h1>

<div id='Changesets'>
  <h2>Recent Changesets</h2>
  <div class='changesets'>
    <table>
      <tr>
        <th>Changeset Id</th>
        <th>Timestamp</th>
        <th>Editor</th>
      </tr>
    <% current_changesets.each do |mc| %>
      <tr>
        <td><%= mc.changeset_id %></td>
        <td><%= mc.changeset.closed_at %></td>
        <td><%= link_to mc.user.name, user_path(mc.user) %></td>
        <td>
        <%= link_to microcosm_changeset_path(mc.id), :class => 'mc-link-button' do %>
          MC
        <% end %>
        </td>
      </tr>
    <% end %>
    </table>
  </div>
</div>
<%= button_to 'Discover 10,000', microcosms_discover_changesets_path, params: {microcosm_id: @microcosm.id, count: 10000} %> (This will take about 1 minute.)

app/views/microcosms/show_editors.html.erb
<p id="notice"><%= notice %></p>

<h1>
Editors of <%= @microcosm.name %>
</h1>

<div id='Changesets'>
  <h2>Recent New Editors</h2>
  <div class='changesets'>
    <table>
      <tr>
        <th>Name</th>
        <th>Changeset</th>
        <th>Timestamp</th>
        <th>Welcomed</th>
      </tr>
      <% recent_first_editors.each do |e| %>
        <tr>
          <td><%= link_to e.name, user_path(e) %></td>
          <td><a href="https://openstreetmap.org/changeset/<%= e.first_edit.changeset_id %>"><%= e.first_edit.changeset_id %></a></td>
          <% #TODO: This is the 1+N problem. %>
          <td><%= e.first_edit.changeset.created_at %></td>
          <td>
            <% if not e.welcomed %>
              <%= link_to welcome_editor_form_path(@microcosm.id, e.id), :class => 'mc-link-button' do %>
                Welcome
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/microcosms/show_members.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @microcosm.name %>
</h1>

<%= link_to 'New', new_organizer_path(@microcosm) %>

<h2>
Members
</h2>
<div class='members'>
  <% @microcosm.members.each do |member| %>
    <ul>
      <li><%= member.user.name %></li>
    </ul>
  <% end %>
</div>

app/views/microcosms/show_organizers.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @microcosm.name %>
</h1>

<%= link_to 'New', new_organizer_path(@microcosm) %>

<div id='Organizers'>
  <h2>Organizers</h2>
  <div class='organizers'>
    <% @microcosm.organizers.each do |organizer| %>
      <ul>
        <li><%= organizer.user.name %></li>
      </ul>
    <% end %>
  </div>
</div>

app/views/microcosms/welcome_editor_form.html.erb
<%= form_tag do %>

  <div class="field">
    <%= label_tag :to %>
    <%= text_field_tag :to, @editor.name, disabled: true %>
  </div>

  <div class="field">
    <%= label_tag :subject %>
    <%= text_field_tag :subject, @subject, disabled: true %>
  </div>

  <div class="field">
    <%= label_tag :body %>
    <%= text_area_tag :body, @welcome_message, disabled: true %>
  </div>

  <p>
<a href="https://www.openstreetmap.org/message/new/Skuwanja?<%= @qs %>" target="_blank">Send Message From OSM</a> ->
  </p>

  <div class="actions">
    <%= submit_tag 'Done' %>
  </div>

<% end %>