config/routes.rb
Rails.application.routes.draw do
  root :to => 'microcosms#index'

  get '/sessions/new' => 'sessions#new'
  match '/auth/:provider/callback' => "sessions#create", via: [:get, :post]
  match '/auth/failure', to: redirect('/'), via: [:get, :post]
  match '/signout' => 'sessions#destroy', :as => :signout, via: [:get, :post]
  resources :events
  resources :organizers
  # This is needed because "new" matches the regex for microcosm names.
  get 'microcosms/new', to: 'microcosms#new'
  get 'microcosms/:key', to: 'microcosms#show_by_key', constraints: { key: /[a-zA-Z]{1,32}/ }
  # TODO: use key by setting constraints:.
  get 'microcosms/:id/editors', to: 'microcosms#show_editors', :as => :editors_of_microcosm
  get 'microcosms/:id/changesets', to: 'microcosms#show_changesets', :as => :changesets_of_microcosm
  get 'microcosms/:id/organizers', to: 'microcosms#show_organizers', :as => :organizers_of_microcosm
  get 'microcosms/:id/members', to: 'microcosms#show_members', :as => :members_of_microcosm
  get 'microcosms/:id/welcome/:editor_id', to: 'microcosms#welcome_editor_form', :as => :welcome_editor_form
  post 'microcosms/:id/welcome/:editor_id', to: 'microcosms#welcome_editor', :as => :welcome_editor
  post '/microcosms/discover_changesets', to: 'microcosms#discover_changesets'
  resources :microcosms
  resources :microcosm_changesets
  resources :members
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/microcosm_changeset.rb
class MicrocosmChangeset < ApplicationRecord
  belongs_to :microcosm
  belongs_to :changeset, class_name: 'Osm::Changeset'
  belongs_to :user
# TODO: scope :unreviewed, { where(review_num: 0) }
end

app/controllers/microcosm_changesets_controller.rb
class MicrocosmChangesetsController < ApplicationController
  before_action :set_microcosm_changeset, only: [:show, :edit, :update, :destroy]

  # GET /microcosm_changesets
  # GET /microcosm_changesets.json
  def index
    @microcosm_changesets = MicrocosmChangeset.last(25)
  end

  # GET /microcosm_changesets/1
  # GET /microcosm_changesets/1.json
  def show
  end

  # GET /microcosm_changesets/new
  def new
    @microcosm_changeset = MicrocosmChangeset.new
  end

  # GET /microcosm_changesets/1/edit
  def edit
  end

  # POST /microcosm_changesets
  # POST /microcosm_changesets.json
  def create
    @microcosm_changeset = MicrocosmChangeset.new(microcosm_changeset_params)

    respond_to do |format|
      if @microcosm_changeset.save
        format.html { redirect_to @microcosm_changeset, notice: 'Microcosm changeset was successfully created.' }
        format.json { render :show, status: :created, location: @microcosm_changeset }
      else
        format.html { render :new }
        format.json { render json: @microcosm_changeset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microcosm_changesets/1
  # PATCH/PUT /microcosm_changesets/1.json
  def update
    respond_to do |format|
      if @microcosm_changeset.update(microcosm_changeset_params)
        format.html { redirect_to @microcosm_changeset, notice: 'Microcosm changeset was successfully updated.' }
        format.json { render :show, status: :ok, location: @microcosm_changeset }
      else
        format.html { render :edit }
        format.json { render json: @microcosm_changeset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microcosm_changesets/1
  # DELETE /microcosm_changesets/1.json
  def destroy
    @microcosm_changeset.destroy
    respond_to do |format|
      format.html { redirect_to microcosm_changesets_url, notice: 'Microcosm changeset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_microcosm_changeset
      @microcosm_changeset = MicrocosmChangeset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def microcosm_changeset_params
      params.require(:microcosm_changeset).permit(:microcosm_id, :changeset_id, :review_num)
    end
end

app/helpers/microcosm_changesets_helper.rb
module MicrocosmChangesetsHelper
end

app/views/microcosm_changesets/_form.html.erb
<%= form_with(model: microcosm_changeset, local: true) do |form| %>
  <% if microcosm_changeset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(microcosm_changeset.errors.count, "error") %> prohibited this microcosm_changeset from being saved:</h2>

      <ul>
      <% microcosm_changeset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :microcosm_id %>
    <%= form.number_field :microcosm_id, id: :microcosm_changeset_microcosm_id %>
  </div>

  <div class="field">
    <%= form.label :changeset_id %>
    <%= form.text_field :changeset_id, id: :microcosm_changeset_changeset_id %>
  </div>

  <div class="field">
    <%= form.label :review_num %>
    <%= form.text_field :review_num, id: :microcosm_changeset_review_num %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/microcosm_changesets/edit.html.erb
<h1>Editing Microcosm Changeset</h1>

<%= render 'form', microcosm_changeset: @microcosm_changeset %>

<%= link_to 'Show', @microcosm_changeset %> |
<%= link_to 'Back', microcosm_changesets_path %>

app/views/microcosm_changesets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Microcosm Changesets</h1>

<table>
  <thead>
    <tr>
      <th>Microcosm</th>
      <th>Changeset</th>
      <th>Review num</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microcosm_changesets.each do |microcosm_changeset| %>
      <tr>
        <td><%= microcosm_changeset.microcosm_id %></td>
        <td><%= microcosm_changeset.changeset_id %></td>
        <td><%= microcosm_changeset.review_num %></td>
        <td><%= link_to 'Show', microcosm_changeset %></td>
        <td><%= link_to 'Edit', edit_microcosm_changeset_path(microcosm_changeset) %></td>
        <td><%= link_to 'Destroy', microcosm_changeset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Microcosm Changeset', new_microcosm_changeset_path %>

app/views/microcosm_changesets/new.html.erb
<h1>New Microcosm Changeset</h1>

<%= render 'form', microcosm_changeset: @microcosm_changeset %>

<%= link_to 'Back', microcosm_changesets_path %>

app/views/microcosm_changesets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Microcosm:</strong>
  <%= @microcosm_changeset.microcosm_id %>
</p>

<p>
  <strong>Changeset:</strong>
  <a href="https://openstreetmap.org/changeset/<%= @microcosm_changeset.changeset_id %>" target="_blank"><%= @microcosm_changeset.changeset_id %></a>
</p>

<p>
  <strong>Review num:</strong>
  <%= @microcosm_changeset.review_num %>
</p>

<p>
  <strong>User id:</strong>
  <%= @microcosm_changeset.user_id %>
</p>

<%= link_to 'Edit', edit_microcosm_changeset_path(@microcosm_changeset) %> |
<%= link_to 'Back', microcosm_changesets_path %>